# Generated by Django 5.0 on 2024-05-21 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_color_alter_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='product_size',
            new_name='product_color',
        ),
    ]
