<<<<<<< HEAD
# Generated by Django 4.2.13 on 2024-05-23 11:17
=======
# Generated by Django 5.0.1 on 2024-05-24 15:17
>>>>>>> d7ec60ba48323d4ac92a9f5b19485fc2ebf24c8d

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_product_size_color_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='product/media/uploads/'),
        ),
    ]
