# Generated by Django 5.0 on 2024-05-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='profile_photo',
            field=models.ImageField(default=None, upload_to='account/images/'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='profile_photo',
            field=models.ImageField(default=None, upload_to='account/images/'),
        ),
    ]
